/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.lines;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "TiLines", id = "ti.lines")
public class TiLinesModule extends KrollModule {

    private static final String LCAT = "TiLinesModule";

    @Kroll.constant
    public static int START_CENTER = 0;
    @Kroll.constant
    public static int START_BOTTOM = 1;

    @Kroll.constant
    public static int TYPE_CURVED = 0;
    @Kroll.constant
    public static int TYPE_STRAIGHT = 1;

    public TiLinesModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

}

